### PR TITLE
Enable test with Github Actions

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
unexpectedly, 

>       line = d.logs.first

returns `[]`.

**Comment by kenhys** [comment]
back to fluentd 0.14.10 + faraday 0.12.0.1, it still fails with empty logs.

**Comment by kenhys** [comment]
at least, if @log_level debug is set, debug log is collectd.

**Comment by kenhys** [comment]
CI has passed. :+1:

**Review by cosmo0920 — APPROVED** [review]
:muscle:

**Pull request merged**
